# frozen_string_literal: true

Item.create(manufacturer_id: nil, value: '4Gb',      item_type: 'ddr3',        qty: 1, price: 2300, category_id: 3, name: 'Память DDRIII 4GB (PC3-12800) 1600MHz [KVR16LN11/4')
Item.create(manufacturer_id: nil, value: '4Gb',      item_type: 'ddr3',        qty: 1, price: 2250, category_id: 3, name: 'Память DDRIII 4GB (PC3-12800) 1600MHz [KVR16N11S8/')
Item.create(manufacturer_id: nil, value: '8Gb',      item_type: 'ddr3',        qty: 1, price: 4200, category_id: 3, name: 'Память DDRIII 8GB (PC3-12800) 1600MHz KVR16N11/8')
Item.create(manufacturer_id: 1,   value: '8Gb',      item_type: 'ddr3',        qty: 2, price: 4200, category_id: 3, name: 'Память DDRIII 8GB (PC3-12800) Kingston1600MHz 1.35')
Item.create(manufacturer_id: nil, value: '10-ports', item_type: 'HUB active',  qty: 1, price: 900,  category_id: 2, name: '10-ports ext. USB CBR CH-310, активный, 10 портов')
Item.create(manufacturer_id: nil, value: '4-ports',  item_type: 'HUB active',  qty: 2, price: 850,  category_id: 2, name: '4-ports ext. USB 2.0 HUB ORIENT TA-400PSN, USB 2.0')
Item.create(manufacturer_id: nil, value: '7-ports',  item_type: 'HUB active',  qty: 1, price: 1100, category_id: 2, name: '7-ports ext. USB 2.0 HUB GR-315UAB Ginzzu USB 3.0/')
Item.create(manufacturer_id: nil, value: '2-ports',  item_type: 'HUB passive', qty: 1, price: 1500, category_id: 2, name: '2-ports ext. USB 2.0 HUB  passiv Greenconnect Хаб')
Item.create(manufacturer_id: nil, value: '4-ports',  item_type: 'HUB passive', qty: 1, price: 450,  category_id: 2, name: '4-ports ext. USB 2.0 Buro BU-HUB4-0.5L-U2.0 4порт.')
Item.create(manufacturer_id: nil, value: '4-ports',  item_type: 'HUB passive', qty: 1, price: 450,  category_id: 2, name: '4-ports ext. USB 2.0 Buro BU-HUB4-0.5R-U2.0 4порт.')
Item.create(manufacturer_id: nil, value: '4-ports',  item_type: 'HUB passive', qty: 1, price: 450,  category_id: 2, name: '4-ports ext. USB 2.0 Buro BU-HUB4-U2.0-Slim 4порт.')
Item.create(manufacturer_id: nil, value: '4-ports',  item_type: 'HUB passive', qty: 1, price: 700,  category_id: 2, name: '4-ports ext. USB 3.0 BURO BU-HUB4-U3.0-S 4порт. че')
Item.create(manufacturer_id: nil, value: '7-ports',  item_type: 'HUB passive', qty: 2, price: 600,  category_id: 2, name: '7-ports ext. USB 2.0 HUB Buro BU-HUB7-1.0-U2.0 7п')
Item.create(manufacturer_id: nil, value: '3-ports',  item_type: 'HUB passive', qty: 1, price: 2100, category_id: 2, name: 'Разветвитель USB-C Hama Aluminium 3порт. серебрист')
Item.create(manufacturer_id: nil, value: '0.50m',    item_type: 'USB',         qty: 3, price: 100,  category_id: 1, name: 'Удлинитель USB 0.5 m')
Item.create(manufacturer_id: nil, value: '0.75m',    item_type: 'USB',         qty: 1, price: 120,  category_id: 1, name: 'Удлинитель USB 0.75 m')
Item.create(manufacturer_id: nil, value: '1.00m',    item_type: 'USB',         qty: 4, price: 150,  category_id: 1, name: 'Удлинитель USB 1 m Гарнизон')
Item.create(manufacturer_id: nil, value: '1.80m',    item_type: 'USB',         qty: 3, price: 150,  category_id: 1, name: 'Удлинитель USB 1.8 m')
Item.create(manufacturer_id: nil, value: '1.80m',    item_type: 'USB',         qty: 1, price: 250,  category_id: 1, name: 'Удлинитель USB 1.8м AM/AF Gembird PRO позол.конт.')
Item.create(manufacturer_id: nil, value: '3.00m',    item_type: 'USB',         qty: 4, price: 200,  category_id: 1, name: 'Удлинитель USB 3 m')
Item.create(manufacturer_id: nil, value: '3.00m',    item_type: 'USB',         qty: 2, price: 300,  category_id: 1, name: 'Удлинитель USB 3 м AM/AF Gembird PRO позол.конт.')
Item.create(manufacturer_id: nil, value: '4.50m',    item_type: 'USB',         qty: 1, price: 350,  category_id: 1, name: 'Удлинитель USB 4.5м AM/AF Gembird PRO позол.конт.')
