AllCops:
  Exclude:
    - 'db/seeds/**/*'
    - 'node_modules/**/*'

Lint/UnusedMethodArgument:
  Exclude:
    - 'app/controllers/api/v1/auth/token.rb'

Lint/UselessAssignment:
  Exclude:
    - 'app/controllers/prices_controller.rb'

Metrics/AbcSize:
  Max: 54

Metrics/BlockLength:
  Max: 33
  Exclude:
    - 'db/schema.rb'
    - 'config/environments/development.rb'

Metrics/MethodLength:
  Max: 30

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/GuardClause:
  Exclude:
    - 'app/controllers/api/v1/auth/authenticable.rb'

Style/IfUnlessModifier:
  Exclude:
    - 'bin/bundle'
    - 'config/deploy.rb'

Style/MissingRespondToMissing:
  Exclude:
    - 'app/controllers/api/v1/auth/authenticable.rb'

Style/MixinUsage:
  Exclude:
    - 'bin/setup'
    - 'bin/update'

Layout/LineLength:
  Max: 190
  Exclude:
    - 'db/seeds.rb'
    - 'config/initializers/devise.rb'

Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - 'db/schema.rb'

Style/FrozenStringLiteralComment:
  Enabled: true

Style/NumericLiterals:
  Exclude:
    - 'db/schema.rb'

Style/StringLiterals:
  Exclude:
    - 'db/schema.rb'
    - 'bin/bundle'
    - 'bin/webpack'
    - 'bin/webpack-dev-server'
    - 'bin/yarn'
    - 'config/environments/production.rb'
    - 'config/puma.rb'
    - 'config/spring.rb'
    - 'test/application_system_test_case.rb'
    - 'test/channels/application_cable/connection_test.rb'


Bundler/OrderedGems:
  Exclude:
    - 'Gemfile'

Layout/ArgumentAlignment:
  Exclude:
    - 'bin/webpack'
    - 'bin/webpack-dev-server'

Layout/EmptyLineAfterGuardClause:
  Exclude:
    - 'bin/bundle'

Layout/ExtraSpacing:
  Exclude:
    - 'db/seeds.rb'

Layout/SpaceAfterComma:
  Exclude:
    - 'db/seeds.rb'

Layout/SpaceAroundOperators:
  Exclude:
    - 'db/seeds.rb'

Layout/SpaceInsideArrayLiteralBrackets:
  Exclude:
    - 'config/environments/production.rb'

Layout/TrailingWhitespace:
  Exclude:
    - 'config/environments/test.rb'

Metrics/CyclomaticComplexity:
  Max: 9

Metrics/PerceivedComplexity:
  Max: 9

Style/ExpandPathArguments:
  Exclude:
    - 'bin/bundle'
    - 'bin/rails'
    - 'bin/rake'

Style/PercentLiteralDelimiters:
  Exclude:
    - 'config/deploy.rb'

Style/PerlBackrefs:
  Exclude:
    - 'bin/bundle'

Style/RedundantBegin:
  Exclude:
    - 'bin/yarn'

Style/SpecialGlobalVars:
  Exclude:
    - 'bin/bundle'

Style/StderrPuts:
  Exclude:
    - 'bin/yarn'

Style/NumericPredicate:
  Exclude:
    - 'spec/**/*'
    - 'app/controllers/bombers_controller.rb'
    - 'app/models/player.rb'

Style/MultilineBlockChain:
  Exclude:
    - 'app/controllers/bombers_controller.rb'

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: false
Layout/SpaceAroundMethodCallOperator:
  Enabled: false
Lint/DeprecatedOpenSSLConstant:
  Enabled: false
Lint/MixedRegexpCaptureTypes:
  Enabled: false
Lint/RaiseException:
  Enabled: false
Lint/StructNewOverride:
  Enabled: false
Style/ExponentialNotation:
  Enabled: false
Style/HashEachMethods:
  Enabled: false
Style/HashTransformKeys:
  Enabled: false
Style/HashTransformValues:
  Enabled: false
Style/RedundantRegexpCharacterClass:
  Enabled: false
Style/RedundantRegexpEscape:
  Enabled: false
Style/SlicingWithRange:
  Enabled: false
Style/CommentedKeyword:
  Enabled: false
Layout/HashAlignment:
  Enabled: false
Layout/FirstHashElementIndentation:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
